services:
  - type: web
    name: CristinaPiccola
    runtime: docker
    plan: free
    branch: main
    rootDir: mypiccola
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /Cristina
    autoDeploy: true
